import React, { useState, useEffect, useRef } from 'react';
import ReactMarkdown from 'react-markdown';
import { AnalysisResult, ChatMessage, ResearchResult } from '../types';
import { FileText, MessageSquare, Send, Sparkles, AlertTriangle, Download, Copy, Microscope, ExternalLink, Loader2 } from 'lucide-react';

interface RightPanelProps {
  analysis: AnalysisResult | null;
  researchResult: ResearchResult | null;
  chatHistory: ChatMessage[];
  onSendMessage: (msg: string) => void;
  onResearch: (query: string) => void;
  isChatLoading: boolean;
  isSearching: boolean;
}

export const RightPanel: React.FC<RightPanelProps> = ({ 
  analysis, 
  researchResult,
  chatHistory, 
  onSendMessage,
  onResearch,
  isChatLoading,
  isSearching
}) => {
  const [activeTab, setActiveTab] = useState<'report' | 'chat' | 'research'>('report');
  const [input, setInput] = useState('');
  const chatEndRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    chatEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [chatHistory, isChatLoading]);

  // Switch to report tab if new analysis comes in
  useEffect(() => {
    if (analysis) {
        setActiveTab('report');
    }
  }, [analysis]);

  const handleSend = () => {
    if (!input.trim()) return;
    onSendMessage(input);
    setInput('');
  };

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      handleSend();
    }
  };

  const handleInitialResearch = () => {
    if (analysis && analysis.findings.length > 0) {
      const primaryFinding = analysis.findings[0].label;
      onResearch(`Recent medical research and clinical trials for ${primaryFinding} in 2024-2025`);
    } else {
       onResearch("Latest advancements in radiology ai 2025");
    }
  };

  return (
    <div className="w-96 border-l border-zinc-800 bg-black flex flex-col h-full">
      {/* Tabs */}
      <div className="flex border-b border-zinc-800 bg-zinc-950">
        <button
          onClick={() => setActiveTab('report')}
          className={`flex-1 py-3 text-sm font-medium flex items-center justify-center transition-all ${
            activeTab === 'report' 
              ? 'text-white border-b-2 border-blue-500 bg-zinc-900' 
              : 'text-zinc-500 hover:text-zinc-300 hover:bg-zinc-900'
          }`}
        >
          <FileText size={16} className="mr-2" />
          Report
        </button>
        <button
          onClick={() => setActiveTab('research')}
          className={`flex-1 py-3 text-sm font-medium flex items-center justify-center transition-all ${
            activeTab === 'research' 
              ? 'text-white border-b-2 border-blue-500 bg-zinc-900' 
              : 'text-zinc-500 hover:text-zinc-300 hover:bg-zinc-900'
          }`}
        >
          <Microscope size={16} className="mr-2" />
          Research
        </button>
        <button
          onClick={() => setActiveTab('chat')}
          className={`flex-1 py-3 text-sm font-medium flex items-center justify-center transition-all ${
            activeTab === 'chat' 
              ? 'text-white border-b-2 border-blue-500 bg-zinc-900' 
              : 'text-zinc-500 hover:text-zinc-300 hover:bg-zinc-900'
          }`}
        >
          <MessageSquare size={16} className="mr-2" />
          Copilot
        </button>
      </div>

      {/* Content Area */}
      <div className="flex-1 overflow-hidden relative">
        {activeTab === 'report' && (
          <div className="h-full overflow-y-auto p-6 text-zinc-300">
            {analysis ? (
              <div className="prose prose-invert prose-sm max-w-none prose-headings:text-blue-400 prose-strong:text-white">
                <div className="flex justify-between items-start mb-6 pb-4 border-b border-zinc-800">
                  <div>
                    <h2 className="text-xl font-bold text-white m-0">Radiology Report</h2>
                    <p className="text-xs text-zinc-500 mt-1">Generated by VLM Agent • Reviewed by none</p>
                  </div>
                  <div className="flex gap-2">
                    <button className="p-1.5 hover:bg-zinc-800 rounded text-zinc-400"><Copy size={16}/></button>
                    <button className="p-1.5 hover:bg-zinc-800 rounded text-zinc-400"><Download size={16}/></button>
                  </div>
                </div>
                
                <ReactMarkdown>{analysis.report}</ReactMarkdown>
                
                <div className="mt-8 pt-4 border-t border-zinc-800 text-[10px] text-zinc-500 flex items-center">
                    <AlertTriangle size={12} className="text-yellow-500 mr-2" />
                    Disclaimer: AI-generated for Clinical Decision Support only. Validation required.
                </div>
              </div>
            ) : (
              <div className="h-full flex flex-col items-center justify-center text-zinc-600">
                <FileText size={48} className="mb-4 opacity-20" />
                <p>No report generated yet.</p>
                <p className="text-xs mt-2">Upload a scan to begin analysis.</p>
              </div>
            )}
          </div>
        )}

        {activeTab === 'research' && (
          <div className="h-full flex flex-col">
            <div className="p-4 border-b border-zinc-800">
              <h3 className="text-sm font-bold text-white mb-2">Latest Research Agent</h3>
              <p className="text-xs text-zinc-400 mb-4">Searches 2024-2025 medical databases for symptoms identified in the scan.</p>
              
              <button 
                onClick={handleInitialResearch}
                disabled={!analysis || isSearching}
                className="w-full py-2 bg-blue-900/30 hover:bg-blue-900/50 border border-blue-800 text-blue-400 rounded text-xs font-medium transition-colors flex items-center justify-center disabled:opacity-50 disabled:cursor-not-allowed"
              >
                 {isSearching ? <Loader2 size={14} className="animate-spin mr-2"/> : <Microscope size={14} className="mr-2"/>}
                 {isSearching ? "Searching Knowledge Graph..." : "Search Research for Findings"}
              </button>
            </div>

            <div className="flex-1 overflow-y-auto p-4 text-zinc-300">
               {researchResult ? (
                 <div className="space-y-6">
                    <div>
                      <h4 className="text-sm font-bold text-white mb-2">Research Summary</h4>
                      <div className="text-xs leading-relaxed text-zinc-400">
                         <ReactMarkdown>{researchResult.summary}</ReactMarkdown>
                      </div>
                    </div>

                    <div>
                      <h4 className="text-sm font-bold text-white mb-2">Sources & Clinical Trials</h4>
                      <div className="space-y-2">
                         {researchResult.sources.length > 0 ? researchResult.sources.map((source, idx) => (
                           <a 
                             key={idx} 
                             href={source.uri} 
                             target="_blank" 
                             rel="noreferrer"
                             className="block p-2 bg-zinc-900 hover:bg-zinc-800 border border-zinc-800 rounded group transition-colors"
                           >
                             <div className="flex items-start justify-between">
                               <span className="text-xs text-blue-400 font-medium line-clamp-2 group-hover:underline">{source.title}</span>
                               <ExternalLink size={12} className="text-zinc-600 group-hover:text-blue-400 flex-shrink-0 ml-2" />
                             </div>
                             <span className="text-[10px] text-zinc-600 truncate block mt-1">{source.uri}</span>
                           </a>
                         )) : (
                           <p className="text-xs text-zinc-600">No direct source links provided.</p>
                         )}
                      </div>
                    </div>
                 </div>
               ) : (
                  <div className="h-full flex flex-col items-center justify-center text-zinc-600">
                    <Microscope size={48} className="mb-4 opacity-20" />
                    <p>No research loaded.</p>
                  </div>
               )}
            </div>
          </div>
        )}

        {activeTab === 'chat' && (
          <div className="flex flex-col h-full">
            <div className="flex-1 overflow-y-auto p-4 space-y-4">
              {/* Intro Message */}
              <div className="flex gap-3">
                 <div className="w-8 h-8 rounded-full bg-blue-900/50 flex items-center justify-center flex-shrink-0">
                    <Sparkles size={14} className="text-blue-400"/>
                 </div>
                 <div className="bg-zinc-900 rounded-lg rounded-tl-none p-3 text-sm text-zinc-300 border border-zinc-800">
                    I am your AI Consultant. I can answer questions about the findings or even <strong>visualize specific organs</strong> if you ask me to "Highlight the [organ]".
                 </div>
              </div>

              {chatHistory.map((msg) => (
                <div key={msg.id} className={`flex gap-3 ${msg.role === 'user' ? 'flex-row-reverse' : ''}`}>
                  <div className={`w-8 h-8 rounded-full flex items-center justify-center flex-shrink-0 ${msg.role === 'user' ? 'bg-zinc-700' : 'bg-blue-900/50'}`}>
                    {msg.role === 'user' ? <div className="text-xs font-bold">DR</div> : <Sparkles size={14} className="text-blue-400"/>}
                  </div>
                  <div className={`rounded-lg p-3 text-sm max-w-[85%] border ${
                    msg.role === 'user' 
                      ? 'bg-zinc-800 text-white border-zinc-700 rounded-tr-none' 
                      : 'bg-zinc-900 text-zinc-300 border-zinc-800 rounded-tl-none'
                  }`}>
                    <ReactMarkdown>{msg.text}</ReactMarkdown>
                  </div>
                </div>
              ))}
              
              {isChatLoading && (
                 <div className="flex gap-3">
                    <div className="w-8 h-8 rounded-full bg-blue-900/50 flex items-center justify-center flex-shrink-0">
                        <Sparkles size={14} className="text-blue-400"/>
                    </div>
                    <div className="bg-zinc-900 rounded-lg rounded-tl-none p-3 text-sm border border-zinc-800">
                        <span className="flex gap-1">
                            <span className="w-1.5 h-1.5 bg-zinc-500 rounded-full animate-bounce"></span>
                            <span className="w-1.5 h-1.5 bg-zinc-500 rounded-full animate-bounce delay-75"></span>
                            <span className="w-1.5 h-1.5 bg-zinc-500 rounded-full animate-bounce delay-150"></span>
                        </span>
                    </div>
                 </div>
              )}
              <div ref={chatEndRef} />
            </div>

            <div className="p-4 border-t border-zinc-800 bg-zinc-950">
              <div className="relative">
                <textarea
                  value={input}
                  onChange={(e) => setInput(e.target.value)}
                  onKeyDown={handleKeyDown}
                  placeholder="Ask to highlight an organ..."
                  className="w-full bg-zinc-900 border border-zinc-800 text-white text-sm rounded-lg pl-4 pr-12 py-3 focus:outline-none focus:border-blue-500 resize-none h-12 min-h-[48px] max-h-32"
                  rows={1}
                />
                <button 
                  onClick={handleSend}
                  disabled={!input.trim() || isChatLoading}
                  className="absolute right-2 top-2 p-1.5 text-blue-500 hover:text-blue-400 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
                >
                  <Send size={18} />
                </button>
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};